### ISSUE TITLE
Feature planning

### ISSUE THREAD

**Issue by Stradivario** [rxdi/deploy#6]
* Create VS code plugin like "flutter get" when you change some module inside package.json automatically it will resolve dependencies graph (if changed)
* implement `.yml` reader like inside `pubspec.yml`

```yml
name: freshrequest
version: 0.0.1
description:
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  http: ^0.12.0
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  built_value: ^6.1.4
  built_collection: ^4.0.0
  memoize: ^2.0.0
  graphql_flutter: ^0.9.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  #flutter_driver:
    #sdk: flutter
  #flutter_test:
    #sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
````
